import { Document } from 'mongoose'

export default interface IPokemon extends Document {
  pokedexNumber?: number,
  abilities?: Array<string>,
  againstBug?: number,
  againstDark?: number,
  againstDragon?: number,
  againstElectric?: number,
  againstFairy?: number,
  againstFight?: number,
  againstFire?: number,
  againstFlying?: number,
  againstGhost?: number,
  againstGrass?: number,
  againstGround?: number,
  againstIce?: number,
  againstNormal?: number,
  againstPoison?: number,
  againstPsychic?: number,
  againstRock?: number,
  againstSteel?: number,
  againstWater?: number,
  attack?: number,
  baseEggSteps?: number,
  baseHappiness?: number,
  baseTotal?: number,
  captureRate?: number,
  classfication?: string,
  defense?: number,
  experienceGrowth?: number,
  heightM?: number,
  hp?: number,
  japaneseName?: string,
  name?: string,
  percentageMale?: number,
  spAttack?: number,
  spDefense?: number,
  speed?: number,
  type1?: string,
  type2?: string,
  weightKg?: number,
  generation?: number,
  isLegendary?: boolean,
  imageUrl?: string,
  spriteUrl?: string
}
